version: "3"

vars:
  VERSION:
    sh: git rev-parse --short HEAD

tasks:
  default:
    cmds:
      - task: build

  run:
    cmds:
      - go run cmd/main.go

  version:
    cmds:
      - echo "{{.VERSION}}"

  build:
    cmds:
      - go build -o build/pbb cmd/main.go
    env:
      CGO_ENABLED: 0

  lint:
    cmds:
      - golangci-lint run

  docker-build:
    cmds:
      - docker build -t pbb:{{.VERSION}} .

  docker-push:
    cmds:
      - task: docker-build
      - docker tag pbb:{{.VERSION}} ghcr.io/sousandrei/paulo-baier-bot:{{.VERSION}}
      - docker push ghcr.io/sousandrei/paulo-baier-bot:{{.VERSION}}

  docker-run:
    cmds:
      - task: docker-build
      - docker container run
        -e TELEGRAM_TOKEN={{.TELEGRAM_TOKEN}}
        --rm
        pbb:{{.VERSION}}
