name: Pull Request

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: arduino/setup-task@v1
        name: Setup Task

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

      - run: task build
