name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-go@v3
        name: Setup Go
        with:
          go-version: 1.19

      - uses: arduino/setup-task@v1
        name: Setup Task

      - run: task build
        name: Build
